package com.mycompany.myapp;


import com.codename1.components.ImageViewer;
import static com.codename1.ui.CN.*;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import java.io.IOException;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.io.NetworkEvent;
import com.codename1.ui.Container;
import com.codename1.ui.util.UIBuilder;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if(err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });        
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
//        Form hi = new Form("Hi World", BoxLayout.y());
//        hi.add(new Label("Hi World"));
//        hi.show();

//          UIBuilder.registerCustomComponent("ImageViewer", ImageViewer.class);
//          UIBuilder builder = new UIBuilder();
//          Container ctn = builder.createContainer(theme, "GUI 1");
//          Form f = (Form) ctn;
//          f.show();

            //init form
            Form form = new Form("Logo Android Code", BoxLayout.y());
            
            //init containers
            Container ctnTop = new Container(BoxLayout.xCenter());
            Container ctnMid = new Container(BoxLayout.xCenter());
            Container ctnBottom = new Container(BoxLayout.xCenter());
            
            //init imageViewers
            //Head
            ImageViewer imgHead = new ImageViewer(theme.getImage("head.png"));
            //LeftHand
            ImageViewer imgLeftHand = new ImageViewer(theme.getImage("hand.png"));
            //Body
            ImageViewer imgBody = new ImageViewer(theme.getImage("body.png"));
            //RightHand
            ImageViewer imgRightHand = new ImageViewer(theme.getImage("hand.png"));
            //LeftLeg
            ImageViewer imgLeftLeg = new ImageViewer(theme.getImage("leg.png"));
            //RightLeg
            ImageViewer imgRightLeg = new ImageViewer(theme.getImage("leg.png"));
            
            
            //Add imageViewers to containers
            //top
            ctnTop.add(imgHead);
            //Mid
            ctnMid.addAll(imgLeftHand, imgBody, imgRightHand);
            //Bottom
            ctnBottom.addAll(imgLeftLeg, imgRightLeg);
            
            //Add containers to form
            form.addAll(ctnTop, ctnMid, ctnBottom);

            form.show();
    }

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }

}
